ALTER TABLE articles ADD COLUMN views_count INT UNSIGNED NOT NULL DEFAULT 0 AFTER is_featured;

ALTER TABLE comments
  ADD COLUMN ip_address VARCHAR(45) NULL AFTER user_id,
  ADD COLUMN reported_count INT UNSIGNED NOT NULL DEFAULT 0 AFTER status;

CREATE TABLE IF NOT EXISTS blocked_commenters (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  ip_address VARCHAR(45) NOT NULL,
  reason VARCHAR(255) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY unique_ip(ip_address)
);
