CREATE TABLE IF NOT EXISTS newsletter_campaigns (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  subject VARCHAR(255) NOT NULL,
  intro TEXT NULL,
  featured_count INT UNSIGNED NOT NULL DEFAULT 0,
  recipients_count INT UNSIGNED NOT NULL DEFAULT 0,
  sent_count INT UNSIGNED NOT NULL DEFAULT 0,
  sent_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS newsletter_campaign_articles (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  campaign_id BIGINT UNSIGNED NOT NULL,
  article_id BIGINT UNSIGNED NULL,
  position INT UNSIGNED NOT NULL DEFAULT 0,
  title VARCHAR(255) NOT NULL,
  url VARCHAR(500) NOT NULL,
  clicks INT UNSIGNED NOT NULL DEFAULT 0,
  FOREIGN KEY(campaign_id) REFERENCES newsletter_campaigns(id) ON DELETE CASCADE,
  FOREIGN KEY(article_id) REFERENCES articles(id) ON DELETE SET NULL,
  INDEX(campaign_id)
);
