CREATE TABLE IF NOT EXISTS draw_rounds (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    draw_date DATE NOT NULL,
    draw_type VARCHAR(255) NOT NULL,
    crs_cutoff SMALLINT UNSIGNED NOT NULL,
    invitations_issued INT UNSIGNED NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY (draw_date, draw_type),
    INDEX (draw_date)
);
